justeece/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('confirm/<token>/<id>',
        VerificationView.as_view(), name='email_confirmation'),    
    path('forgotpassword/', ForgotPasswordRequestView.as_view(),
        name="forgot-password"),
    path('reset_password/<emailtype>/<token>/<id>',
        ResetPasswordView.as_view(), name='resetpassword'),
    path('reset-password-success/', ResetPasswordSuccessView.as_view(),
        name="reset_password_success"),   
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_list/<data>', UserListView.as_view(), name='profile'),
    path('email-verification-confirmation/', EmailVerificationConfirmationLinkView.as_view(), 
        name="email_verification_confirmation"),
    path('resendverification/<email>',
        ResendVerificationToken.as_view(), name='resendverification'),
    path('personal-details/',
        PersonalDetailsView.as_view(), name='personal-details'),
    path('dynamic-dropdonws/',
        DynamicDropdowns.as_view(), name='dynamic-dropdonws'),
    path('search_user/',
        SearchUserView.as_view(), name='search-user'),  
    path('create_cover_letter/',
        CreateCoverLetterView.as_view(), name='create-cover-letter'),  
    path('send_cover_letter/',
        SendCoverLetterView.as_view(), name='send-cover-letter'),   
    path('send_reference_email/',
        SendReferenceEmailView.as_view(), name='send-reference-email'),   
    path('add_reference/<int:id>',reference, name='add-reference'),
    path('unsubscribe/<int:id>',unsubscribe, name='unsubscribe')

]

justeece/app/urls.py
from django.contrib import admin
from django.urls import path
from app.views import TestimonialView, SearchView, AboutUsView

app_name = 'app'

urlpatterns = [
    path('testimonial/', TestimonialView.as_view(), name='testimonial'),
    path('search/', SearchView.as_view(), name='search'),
    path('aboutus/', AboutUsView.as_view(), name='about-us'),
]

justeece/justeece/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import DashboardView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='signup'),
    path('providers/',  SignupView.as_view(), name='provider'),
    path('vendors/',  SignupView.as_view(), name='vendor'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contracts/', include('contracts.urls', namespace='contracts')),
    path('app/', include('app.urls', namespace='app')),
    path('manager/', include('manager.urls', namespace='manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

justeece/accounts/views/password.py
from django.views.generic import FormView, TemplateView
from django.shortcuts import redirect,render
from django.contrib.auth import logout as auth_logout,login as auth_login
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.utils import timezone
from accounts.forms import ForgotPasswordRequestForm, ResetPasswordForm
from accounts.models import UserSecurityToken
from app.decorators import anonymous_only,anonymous_view
from app.string import Hash


@anonymous_view(redirect_to='/accounts/success')
class ForgotPasswordRequestView(FormView):
    ''' 
    ForgotPassword Request View 
    '''
    form_class = ForgotPasswordRequestForm
    template_name = 'accounts/forgot_password.html'

    def get(self, request, *args, **kwargs):
        '''
        get request
        '''
        auth_logout(request)
        return super(ForgotPasswordRequestView, self).get(request, *args, **kwargs)

    def get_form_kwargs(self):
        ''' get form kwargs '''
        data = super(ForgotPasswordRequestView, self).get_form_kwargs()
        data.update({'request': self.request})
        return data

    def form_valid(self, form):
        '''form valid'''
        _ = self.__class__
        form.save() 
        return redirect(reverse('accounts:forgot-password'))

@anonymous_view(redirect_to='/accounts/success')
class ResetPasswordView(FormView):
    '''
    Reset Password form
    '''
    template_name = 'accounts/reset_password.html'
    form_class = ResetPasswordForm
    valid_token = ''

    def get(self, request, *args, **kwargs):
        '''get request'''
        valid_link= self._is_valid_link(*args)
        if valid_link == 'expired':
            self.template_name = 'forgot_password_link_expired.html'
            return render(request, self.template_name)
        return super(ResetPasswordView, self).get(request, *args, **kwargs)

    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        try:
            return super(ResetPasswordView, self).dispatch(request, *args, **kwargs)
        except UserSecurityToken.DoesNotExist:
            return HttpResponseRedirect(reverse('login'))

    def get_form_kwargs(self):
        '''update form args '''
        data = super(ResetPasswordView, self).get_form_kwargs()
        self.valid_token = self._is_valid_link()
        data.update({'request': self.request,
                     'token': self.valid_token
                     })
        return data

    def form_valid(self, form):
        ''' form valid '''
        form.save()
        return super(ResetPasswordView, self).form_valid(form)

    def get_success_url(self):
        '''get succcess url '''
        _ = self.__class__
        return reverse('accounts:reset_password_success')

    def get_context_data(self, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)
        email = Hash.decrypt_string(self.kwargs['id'].encode('utf-8'))
        email = email.decode('utf-8')
        context.update({'title': 'Reset Password',
                        'validity': self.valid_token,
                        'emailtype': self.kwargs['emailtype'],
                        'email': email})
        return context

    def _is_valid_link(self):
        '''check if change password link is valid '''
        email = Hash.decrypt_string(self.kwargs['id'].encode('utf-8'))
        email = email.decode('utf-8')
        valid_token = None

        try:
            user = get_user_model().objects.filter(email__iexact=email).get()
            try:
                user_token = UserSecurityToken.objects.filter(token=self.kwargs['token'],
                                                              extras=email,
                                                              token_type=UserSecurityToken.FORGOT_PASSWORD).get()
                if not user.is_active:
                    valid_token = 'not-active'
                elif user_token.expire_date > timezone.now():
                    valid_token = user_token
                else:
                    valid_token = 'expired'
            except UserSecurityToken.DoesNotExist:
                valid_token = 'invalid'
        except get_user_model().DoesNotExist:
            valid_token = 'invalid'
        return valid_token

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(**self.get_form_kwargs())

class ResetPasswordSuccessView(TemplateView):
    """
    View shows success page post successful forgot password form.
    """
    
    template_name   = 'accounts/updated-password-confirmation.html'

justeece/accounts/views/verificationlinks.py
'''
verification steps
'''
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View
from django.urls import reverse_lazy
from django.http.response import HttpResponseRedirect, JsonResponse
from app.string import Hash
from app import messages
from accounts.models import UserSecurityToken

class ResendVerificationToken(View):
    ''' 
    Resend Verification Token 
    '''

    def get(self, *args, **kwargs):
        user = get_user_model().objects.filter(email__iexact=kwargs['email']).get()
        try:
            ''' filtering email from UserSecurityToken '''
            user_token = UserSecurityToken.objects.filter(
                extras=kwargs['email'], token_type=UserSecurityToken.ACCOUNT_ACTIVATION_TOKEN).last()
            ''' user token validate'''
            if user_token:
                user_token.expire_date = timezone.now()
                user_token.save()
            token = UserSecurityToken.create_activation_token(
                kwargs['email'],user )
            token.send_verify_token_email(self.request)

            '''only for ajax request'''
            if self.request.is_ajax():
                data = {'success': False,
                        'message': messages.VERIFICATION_EMAIL_SENT}
                data['success'] = True


        except UserSecurityToken.DoesNotExist:
            data = {}
            data['success'] = False
            data['message'] = messages.USER_DOESNOT_EXIST


        if self.request.is_ajax():
            return JsonResponse(data)

        else:
            return HttpResponseRedirect(reverse_lazy('accounts:email_verification_confirmation'))

class VerificationView(View):
    '''
    Verify user account and redirects to profile's page
    '''
    template_name = 'accounts/email/email-verification-success-message.html'

    def get(self, request, *args, **kwargs):
        valid_link, email = self._is_valid_link(*args, **kwargs)

        validity = 'valid_token'
        if valid_link == 'expired':
            validity = 'expired-token'
            self.template_name = 'accounts/email/link-expired.html'
        return render(request, self.template_name, {'validity': validity, 'email': email})

    def get_context_data(self, **kwargs):
        context = super(VerificationView, self).get_context_data(**kwargs)
        context.update({'title': 'Verification'})
        return context

    def _is_valid_link(self, *args, **kwargs):
        '''Check if change password link is valid '''
        email = Hash.decrypt_string(kwargs['id'].encode('utf-8'))
        email = email.decode('utf-8')
        validlink = None
        user_email = ''
        try:
            user = get_user_model().objects.filter(email__iexact=email).get()
            try:
                token = kwargs['token']
                user_token = UserSecurityToken.objects.filter(token=token,
                                                              extras=email).get()
                ''' checking the expiry date of user token '''                  
                if user_token.expire_date > timezone.now():
                    user_token.expire_date = timezone.now()
                    user_token.save()
                    user.verified_date = timezone.now()
                    user.is_verified = True 
                    user.is_active = True
                    user.save()
                    validlink = True
                else:
                    validlink = 'expired'
                    user_email = user_token.user.email

            except UserSecurityToken.DoesNotExist:
                validlink = 'invalid'
        except get_user_model().DoesNotExist:
            validlink = 'invalid'
        return validlink, user_email

justeece/accounts/templates/accounts/add_reference.html
{% extends 'layout.html' %}{% load static %} {% load static %} 
{% block extrastyles %}
  <link rel="stylesheet" href="{% static '/css/personal-detail/index.css' %}" />  
{% endblock %} 

{% block content %}
  <div class="content-wrapper">
    <div class="container">
      <div class="row ref-wrapper">
        <div class="col-md-6 border-right d-flex justify-content-center text-center">
            <div class="ref-head">
              <img src="{% static 'images/star.svg' %}" alt="">
              <h3>Request a Reference</h3>
              <img id='trophy' src="{% static 'images/trophy.svg' %}" alt="">
              <p>Why referencing is so important?</p>
              <ul>
                <li><img src="{% static 'images/single_star.svg' %}" alt=""><h5>Avoids plagiarism</h5></li>
                <li><img src="{% static 'images/single_star.svg' %}" alt=""><h5>Aknowledges prior research</h5></li>
                <li><img src="{% static 'images/single_star.svg' %}" alt=""><h5>Adds credibility</h5></li>
              </ul>
            </div>
            
        </div>
        <div class="col-md-6 d-flex justify-content-center text-center">
          <div class="ref-form">
            <p id="top-para">Providers with references are 7 times more <br>
              likely to be hired</p>
            <p id="middle-para">Reference can be friends,  <br>
              family or past clients</p>
              <form action="{% url 'accounts:send-reference-email' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                  <div class="col-md-6 mb-3">
                    <label for="validationServer01">Reference Email</label>
                    <input type="email" class="form-control" id="" value="" name="email" required>
                    
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="validationServer02">Reference Name</label>
                    <input type="text" class="form-control" id="" value="" name='name' required>
                    
                  </div>
                </div>
                <button id='ref-btn' class="btn btn-primary float-right" type="submit">Submit form</button>
                <div class="buttons-wrapper" style="margin-top: 100px;">
                  <a id="ref-con" href="{% url 'accounts:dashboard'%}">I’ll do it later</a>
                </div>
                
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

justeece/accounts/templates/accounts/cover_letter.html
{% extends 'layout.html' %}{% load static %}
{% block extrastyles %}
<link
rel="stylesheet"
href="{% static 'css/modal/index.css' %}"
/>
<style>
  ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color:    #909;
}
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
   color:    #909;
   opacity:  1;
}
::-moz-placeholder { /* Mozilla Firefox 19+ */
   color:    #909;
   opacity:  1;
}
:-ms-input-placeholder { /* Internet Explorer 10-11 */
   color:    #909;
}
::-ms-input-placeholder { /* Microsoft Edge */
   color:    #909;
}

input.cover_letter_box::placeholder { /* Most modern browsers support this now. */
    top:10px;
    padding-left: 15px;
    position: absolute;
}
.cover_letter_box {
    min-height: 176px;
}
.cover_letter_label {
    font-family: "Helvetica", sans-serif;
    font-size: 12px;
    font-weight: bold;
    padding-left: 15px;
    width: 100%;
    margin-bottom: 0px !important;
}

.register-form :nth-child(n) {
    margin-top: 0px;
}

</style>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="d-flex flex-column justify-content-center wrapper-form">
          <div class="form-wrapper">
              {% if request.user.cover_letter %}
                <h2 class="form-header">Edit cover letter</h2>
              {% else %}
                <h2 class="form-header">Create cover letter</h2>
              {% endif %}
            <form method="POST" action="{% url 'accounts:create-cover-letter' %}" class="register-form" id="coverLetter">
              {% csrf_token %}
              <label class="cover_letter_label">Cover letter</label>
              <div class="form-group">

                <textarea
                id="subject"
                placeholder="Describe yourself..."
                class="form-field form-control cover_letter_box"
                name="cover_letter"
                required
              >{% if request.user.cover_letter %}{{request.user.cover_letter}}{% endif %}</textarea>
              </div>
              <button type="button" class="btn btn-primary form-btn create_cover_submit">
                save
              </button>
              <div class="invalid-tooltip-message text-danger"> {{form.cover_letter.errors.0}} </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="createCoverLetterThanks" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered common-modal" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <img src="{% static 'images/resume-pana1.svg' %}" alt="resume" />
          <p class="bold">Thank you! Your cover letter has been created</p>
          <p>Thank you! Your cover letter has been created

          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary back_btn">Back to the profile page</button>
        </div>
      </div>
    </div>
  </div>
<!--Modal-->
{% endblock %}

{% block extrascript %}
<script>
    $(document).on('click','.create_cover_submit',function(event){
        $.ajax({
              url: '/accounts/create_cover_letter/',
              type: 'post',
              data: $('#coverLetter').serialize(),
              dataType: 'json',
              success:function(response){
                $('#createCoverLetterThanks').modal('show');
              }
          });
    });

    $('.back_btn').on('click',function(){
        window.location.href = '/accounts/profile'
      })  
</script>

{% endblock %}

justeece/accounts/templates/accounts/error.html
error

justeece/accounts/templates/accounts/forgot_password.html
{% extends 'layout.html' %}{% load static %}

{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="form-wrapper">
          <h2 class="form-header">Forgot Password</h2>
          <form method="POST" class="register-form">
            {% csrf_token %}
            <div class="form-group">
              <input
                type="text"
                id="femail"
                name="{{form.email.name}}"
                placeholder="Email"
                class="form-field form-control"
              />
            </div>
            <button type="submit" class="btn btn-primary form-btn">
              Submit
            </button>
            <div class="terms-condition-text already-loggedin">
              Don't have an account? <a href="{% url 'accounts:signup' %}"><span>Sign up</span></a>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

justeece/accounts/templates/accounts/login.html
{% extends 'layout.html' %}{% load static %}

{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="form-wrapper">
          <h2 class="form-header">Log in</h2>
          <form method="POST" class="register-form">
            {% csrf_token %}
            <div class="form-group">
              <input
                type="text"
                id="femail"
                name="{{form.email.name}}"
                placeholder="Email"
                class="form-field form-control"
                value="{% if form.email.value %}{{form.email.value}}{% endif %}"
              />
            </div>
            <div class="form-group">
              <input
                type="password"
                id="fpassword"
                name="{{form.password.name}}"
                placeholder="Password"
                class="form-field form-control"
              />
            </div>
            {% if form.non_field_errors %}
            <div class="non-field-errors">
              {% for err in form.non_field_errors %}{{error.code}}
              {% if err == "PLEASE_ACTIVATE" %}
                <p class="text-danger">Seems like your account is not activated yet, please <a style="color:green" href="{% url 'accounts:resendverificationemail' email %}" >'click here'</a> to receive the account activation email again.</p>
                {% else %}
                <p class="text-danger">{{ err }}</p>
                {% endif %}
              {% endfor %}
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary form-btn">
              Login
            </button>
            <div class="terms-condition-text already-loggedin">
              Don't have an account? <a href="{% url 'accounts:signup' %}"><span>Sign up</span></a>
            </div>
            <div class="terms-condition-text already-loggedin forget-password">
              <a href="{% url 'accounts:forgot-password' %}"><span>Forget Password?</span></a>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

justeece/accounts/templates/accounts/personal_details.html
{% extends 'layout.html' %}{% load static %} {% load static %} 
{% block extrastyles %}
  <link rel="stylesheet" href="{% static 'css/contractPage/index.css' %}" />
  <link
    rel="stylesheet"
    href="{% static 'lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css' %}"
  />
  <link
    rel="stylesheet"
    href="{% static 'lib/bootstrap-datepicker-master/dist/css/bootstrap-datepicker.min.css' %}"
  />
  <link rel="stylesheet" href="{% static '/css/personal-detail/index.css' %}" />
  
  {% if not request.user.profile_added%}
  <!-- Code to make navbar invisible. attempt to prevent users from not filling data-->
  <style>
    .navbar-wrapper,
    .content-footer-container {
      display: none !important;
    }
  
    .content-wrapper {
      margin-top: -120px;
    }
  </style>
  {% endif %} {% endblock %} {% block content %}
  <div class="content-wrapper">
    <div class="container">
      <div class="form-wrapper contact-page-parent-wrapper personal-detail">
        <h2 class="form-header">Personal details</h2>
        <h5 class="form-header-small">{{request.user.email}}</h5>
        <form
          class="contact-page"
          method="POST"
          action=""
          id="personal_details_form"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-group">
            <label for="profilephoto">Profile Photo</label>
            <div class="drop-zone">
              <span class="drop-zone__prompt"
                >Drag and drop or
                <span class="browse">browse</span></span
              >
              <input
                type="file"
                value="{% if request.user.profile_photo %}{{request.user.profile_photo.url}}{% else %}{% static 'images/profile_img.png' %} {% endif %}"
                class="drop-zone__input"
                name="{{form.profile_photo.name}}"
                accept="image/*"
              />
            </div>
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.profile_photo.errors.0}}
          </div>
          <div class="form-group">
            <label for="lname">Phone Number</label>
            <input
              value="{% if form.phone_number.value %}{{form.phone_number.value}}{% endif %}"
              type="tel"
              name="{{form.phone_number.name}}"
              placeholder="Enter Phone Number"
              class="form-field form-control"
            />
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.phone_number.errors.0}}
          </div>
      <div class="form-group">
            <label for="subject">Occupation</label>
            <input
              id="subject"
              name="{{form.occupation.name}}"
              placeholder="Enter your Occupation here..."
              class="form-field form-control"
              value="{% if form.occupation.value %}{{form.occupation.value}}{% endif %}"
            />
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.occupation.errors.0}}
          </div>

          <input
              id="country"
              name="{{form.country.name}}"
              class="form-field form-control"
              value="{% if form.country.value %}{{form.country.value}}{% endif %}"
              type="hidden"
            />
            <input
            id="city"
            name="{{form.city.name}}"
            class="form-field form-control"
            value="{% if form.city.value %}{{form.city.value}}{% endif %}"
            type="hidden"
          />
          <div class="form-group">
            <label for="subject">About your business/occupation</label>
            <textarea
              id="subject field"
              name="{{form.about_me.name}}"
              placeholder="Describe your business, minimum of 50 characters"
              class="form-field form-control"
              onkeyup="countChar(this)"
            >{% if request.user.about_me %}{{request.user.about_me}}{% endif %}</textarea>
            <p
              class="ml-3 mt-1 char_counter"
              style="font-size: 10px; padding: 0; margin: 0"
            >
              Characters (Not less than 50): <span id="charNum">0</span>
            </p>
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.about_me.errors.0}}
          </div>
  
          <div class="form-group">
            <label for="subject">
              <em class="fab fa-instagram icon-color"></em> Instagram
              Username</label
            >
            <input
              id="subject"
              name="{{form.ig_username.name}}"
              placeholder="Enter your Instagram username here..."
              class="form-field form-control"
              value="{% if form.ig_username.value %}{{form.ig_username.value}}{% endif %}"
            />
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.ig_username.errors.0}}
          </div>
  
          <div class="form-group">
            <label for="subject">
              <em class="fab fa-twitter icon-color"></em> Twitter
              Handle</label
            >
            <input
              id="subject"
              name="{{form.twitter_handle.name}}"
              placeholder="Enter your Twitter handle here..."
              class="form-field form-control"
              value="{% if form.twitter_handle.value %}{{form.twitter_handle.value}}{% endif %}"
            />
          </div>
          <div class="invalid-tooltip-message text-danger">
            {{form.twitter_handle.errors.0}}
          </div>
  
          <div class="buttons-wrapper">
            <button type="submit" class="btn btn-primary form-btn">
              Save and continue
            </button>
            <button
              type="button"
              class="btn btn-outline-primary form-btn back_btn"
            >
              Back to dashboard
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endblock %} {% block extrascript %}
  <script src="{% static '/js/personal-detail.js' %}"></script>
  <script>
    $(document).ready(function () {
      // Adding more language
      $("#add_language").on("click", function () {
        if (!$("#language_div").children().eq(1).hasClass("d-none")) {
          $("#language_div").children().last().removeClass("d-none");
        }
        $("#language_div").children().eq(1).removeClass("d-none");
      });
  
      loadDropdowns = (url, data, load_id) => {
        $.ajax({
          url: url,
          async: false,
          type: "GET",
          data: data,
          success: function (data) {
            const options = data.dropdown_options;
            $("#" + load_id).empty();
            $("#" + load_id).append(
              "<option value='' selected>Select Option</option>"
            );
  
            if (data.dropdown_options.length > 0) {
              for (const key in options) {
                $("#" + load_id)
                  .append(
                    "<option value='" +
                      options[key][0] +
                      "' data-value='" +
                      options[key][2] +
                      "'>" +
                      options[key][1] +
                      "</option>"
                  )
                  .trigger("change");
              }
              $(".selectpicker").selectpicker("refresh");
            }
          },
        });
      };
  
      $("#country").on("change", function (e) {
        id = $(this).val();
        if (id) {
          url = "{% url 'accounts:dynamic-dropdonws' %}";
          data = { id: id, dropdown_type: "CITY" };
          loadDropdowns(url, data, "city");
        }
      });
    }); //ready
  
    $(".back_btn").on("click", function () {
      window.location.href = "/accounts/dashboard";
    });
  </script>
  <script>
    function countChar(val) {
      var len = val.value.length;
      if (len >= 2000) {
        val.value = val.value.substring(0, 2000);
      } else {
        $('#charNum').text(len);
      }
    };
  </script>
  <script>
    function ipLookUp () {
      fetch('https://api.geoapify.com/v1/ipinfo?apiKey=f46b0052aa4c48a6a7c0d58ffb7bc90f')
        .then(resp => resp.json())
        .then((userLocationData) => {
          $("#country").val(userLocationData.country.name);
          $("#city").val(userLocationData.city.name);
	        console.log(userLocationData.city.name);
          });
    }
    ipLookUp()
  </script>
  {% endblock %}
  

justeece/accounts/templates/accounts/unsubcribe.html
{% extends 'layout.html' %}{% block content %} {% load i18n %} {% block pageclass %} {% endblock %} {% load staticfiles static %}
<title>unsubscibe</title>
<div class="content-wrapper">
<div class="content">
    <div class="form-wrapper">
        <h2 class="text-center">{{email}}</h2>
        <p class="w-auto mx-auto text-center">{{message}}</p>
    </div>
</div>
</div>

{% endblock %}

justeece/accounts/templates/accounts/updated-password-confirmation.html
{% extends 'layout.html' %}{% block content %} {% load i18n %} {% block pageclass %} {% endblock %} {% load staticfiles static %}
<title>Password Updated!</title>
<div class="content-wrapper">
<div class="content">
    <div class="form-wrapper">
        <h2 class="text-center">Password Updated!</h2>
        <p class="w-auto mx-auto text-center">Your password has been updated successfully!<br> Click below button to Sign In</p>
        <form class="mt-4 sign-up">
            <div class="navbar-text">
                <a href="{% url 'accounts:login' %}" class="btn btn-primary" >Login</a>
            </div>
              
        </form>
    </div>
</div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->


{% endblock %}