justeece/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('confirm/<token>/<id>',
        VerificationView.as_view(), name='email_confirmation'),    
    path('forgotpassword/', ForgotPasswordRequestView.as_view(),
        name="forgot-password"),
    path('reset_password/<emailtype>/<token>/<id>',
        ResetPasswordView.as_view(), name='resetpassword'),
    path('reset-password-success/', ResetPasswordSuccessView.as_view(),
        name="reset_password_success"),   
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_list/<data>', UserListView.as_view(), name='profile'),
    path('email-verification-confirmation/', EmailVerificationConfirmationLinkView.as_view(), 
        name="email_verification_confirmation"),
    path('resendverification/<email>',
        ResendVerificationToken.as_view(), name='resendverification'),
    path('personal-details/',
        PersonalDetailsView.as_view(), name='personal-details'),
    path('dynamic-dropdonws/',
        DynamicDropdowns.as_view(), name='dynamic-dropdonws'),
    path('search_user/',
        SearchUserView.as_view(), name='search-user'),  
    path('create_cover_letter/',
        CreateCoverLetterView.as_view(), name='create-cover-letter'),  
    path('send_cover_letter/',
        SendCoverLetterView.as_view(), name='send-cover-letter'),   
    path('send_reference_email/',
        SendReferenceEmailView.as_view(), name='send-reference-email'),   
    path('add_reference/<int:id>',reference, name='add-reference'),
    path('unsubscribe/<int:id>',unsubscribe, name='unsubscribe')

]

justeece/app/urls.py
from django.contrib import admin
from django.urls import path
from app.views import TestimonialView, SearchView, AboutUsView

app_name = 'app'

urlpatterns = [
    path('testimonial/', TestimonialView.as_view(), name='testimonial'),
    path('search/', SearchView.as_view(), name='search'),
    path('aboutus/', AboutUsView.as_view(), name='about-us'),
]

justeece/contracts/urls.py
from django.contrib import admin
from django.urls import path
from contracts.views import *

app_name = 'contracts'

urlpatterns = [
    path('', ContractsLandingPageView.as_view(), name='contract-landing-page'),
    path('create_contract', CreateContractView.as_view(), name='create-contract'),
    path('create_contract_type/', CreateContractTypeView.as_view(), name='create-contract-type'),
    path('render_contract_type/',CreateContractTypeView.as_view(), name='render-contract'),
    # path('edit_contract/<int:contract_id>', CreateContractView.as_view(), name='edit-contract'),
    path('edit_contract/<int:contract_id>', EditContractView.as_view(), name='edit-contract'),
    path('contract_confirmation/<int:contract_id>', ContractConfirmationView.as_view(), name='contract-confirmation'),
    path('contract_completion/', ContractCompletionView.as_view(), name='contract-completion'),
    path('successview/', SuccessView.as_view(), name='successview'),
    path('submit_contract/<int:contract_id>', SubmitContract.as_view(), name='submit-contract'),
    path('contracts/', MyContractsView.as_view(), name='my-contracts'),
    path('contract_detail/<int:id>', ContractDetailView.as_view(), name='contract-detail'),
    path('update_contract/<int:id>', UpdateContractView.as_view(), name='update-contract'),
    path('contract_template/', TemplateContractView.as_view(), name='contract-template'),
    path('cancel_complete_contract/<int:id>', CancelCompleteContractView.as_view(), name='cancel-complete-contract'),
    path('search/', TemplateContractSearchView.as_view(), name='templatesearch'),
]

justeece/justeece/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import DashboardView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='signup'),
    path('providers/',  SignupView.as_view(), name='provider'),
    path('vendors/',  SignupView.as_view(), name='vendor'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contracts/', include('contracts.urls', namespace='contracts')),
    path('app/', include('app.urls', namespace='app')),
    path('manager/', include('manager.urls', namespace='manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

justeece/manager/urls.py
from django.urls import path

from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.statistics, name='statistics'),
]

justeece/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="em">
  <head>
    <title></title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="{{csrf_token}}">
    <link rel="stylesheet" href="{% static 'lib/fontawesome/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/topbar/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/common/form/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/register/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/common/common.css' %}" />
    <link rel="icon" type="image/png" href="{% static 'images/logo.jpg' %}"/>
    <style>
      .alert-container {
      font-family: "Helvetica", sans-serif;
      font-style: normal;
      font-stretch: normal;
      line-height: normal;
      letter-spacing: normal;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-rendering: optimizeLegibility;
    }

    .alert-container {
      -moz-border-radius: 4px;
      -webkit-border-radius: 4px;
      -ms-border-radius: 4px;
      border-radius: 4px;
    }

    .alert-container {
      position: fixed;
      top: 90px;
      right: 0%;
      width: 100%;
      display: none;
      z-index: 9999;
    }

    .alert-container .alert {
      text-align: center;
      padding: 17px 10px 17px 10px;
      height: auto;
      font-size: 14px;
      margin: 0px auto;
      color: #721c24;
      max-width: 260px;
      background-color: #f8d7da;
      border-color: #f5c6cb;
    }

    #badge{
      background: #1877f2;
      padding: 5px;
      border-radius: 50%;
      color: white;
      font-size: 8px;
    }
    </style>
    {% block extrastyles %}{% endblock %}
    
  </head>
  <body>
    {% if messages %}
    <div class="alert-container">
      <div class="alert">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
      </div>
    </div>
    {% endif %} 
    <div class="navbar-wrapper">
      <!-- navbar for logged in page start -->
      <nav class="navbar navbar-expand-md fixed-top navbar-register">
        <div class="container">
          <div class="search-container hidden-search-bar">
            <form action="{% url 'app:search' %}" method="get">
              <input
                class="search"
                id="searchleft"
                type="search"
                name="search"
                placeholder="Search"
                value="{{search_term}}"
              />
              <label class="button searchbutton" for="searchleft"
                ><img src="{% static 'images/search-icon.svg' %}" alt="search"
              /></label>
            </form>
          </div>
          <div class="navbar-logo-wrapper">
            <a class="navbar-brand" href="{% url 'accounts:dashboard' %}"
              ><div class="logo">
                <img alt="logo" src="{% static 'images/new_logo.svg' %}" />
              </div>
              <!-- <div class="logo-text">
                <span class="upper-text">JUSTEECE</span
                ><span class="lower-text">Find <span>Trust</span></span>
              </div> -->
              </a>
          </div>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavbar"
            onclick="openNav()"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <form class="form-inline" action="{% url 'app:search' %}" method="get">
            {% csrf_token %}
            {% if 'providers' not in request.path %}
            <input
              class="form-control mr-sm-2"
              type="search"
              placeholder="Search for providers"
              aria-label="Search"
              name="search"
              value="{{search_term}}"
            />
            <button class="btn my-2 my-sm-0" type="submit">
              <img src="{% static 'images/search-icon.svg' %}" alt="search" />
            </button>
            {% endif %}
          </form>
          <div id="myNav" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"
              ><img src="{% static 'images/closeBtn.svg' %}" alt=""
            /></a>
            <div class="overlay-content">
              <a href="#">Home</a>
              <a href="{% url 'app:about-us' %}">About us</a>
              {% if request.user.is_authenticated %}
              <a href="{% url 'accounts:logout' %}">Logout</a>
               {% else %}
               <a href="{% url 'accounts:signup' %}">Sign up</a>
               <a href="{% url 'accounts:login' %}">Log in</a>                
               {% endif %}
            </div>
          </div>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url  'contracts:my-contracts' %}">Contracts <img src="{% static 'images/arrow_down.svg' %}" alt="">          
                      {% if request.user.get_contracts_pending > 0 %}
                      <span id="badge">
                          {{request.user.get_contracts_pending}}
                      </span>
                      {%endif%}
                    </a>
                  </li>
                  {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about-us' %}">About us</a>
              </li>
              {% if request.user.is_authenticated %}
              <a class="btn btn-primary" href="{% url 'contracts:contract-template' %}">New Contract</a>
              {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
            <div class="navbar-text">
                <a class="btn btn-secondry nav_btn" href="{% url 'accounts:logout' %}">
                  <span>Log out</span>
                </a>
                <a class="btn btn-secondry nav_btn" href="{% url 'accounts:profile' %}">
                  <img
                    class="card-img-top"
                    src="{% if request.user.profile_photo %}{{request.user.profile_photo.url}}{% else %}{% static 'images/profile_img.png' %} {% endif %}"
                    alt=""
                  />
                </a>
              </div>
              {% else %}
            <div class="navbar-text">
              <a class="btn btn-secondry nav_btn" href="{% url 'accounts:login' %}">Log in</a>
              <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Sign Up</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
      <!-- navbar for logged in page end -->
      <!-- navbar for unlogged in page start -->
      <!-- <nav class="navbar navbar-expand-md fixed-top">
        <div class="container">
          <div class="navbar-logo-wrapper">
            <a class="navbar-brand" href="#"
              ><div class="logo">
                <img src="../../Assests/images/new_logo.svg" />
              </div>
              <div class="logo-text">
                <span class="upper-text">JUSTEECE</span
                ><span class="lower-text">Find <span>Trust</span></span>
              </div></a
            >
          </div>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="#">About us</a>
              </li>
            </ul>
            <div class="navbar-text">
              <button class="btn btn-secondry">Log in</button>
              <button class="btn btn-primary">Sign in</button>
            </div>
          </div>
        </div>
      </nav> -->
      <!-- navbar for unlogged in page end -->
    </div>
    {% block content %} {% endblock %}
    <div class="content-footer">
        <div class="container content-footer-container">
          <a class="navbar-brand" href="#"
            ><div class="logo"><img alt="logo" src="{% static 'images/new_logo.svg' %}" /></div>
            <!-- <div class="logo-text">
              <span class="upper-text">JUSTEECE</span
              ><span class="lower-text">Find <span>Trust</span></span>
            </div> -->
            </a>
          <div class="footer-nav-tabs">
            <a>Home</a><a href="{% url 'app:about-us' %}">About us</a>
            {%if request.user.is_staff %}
            <a href="{% url 'manager:statistics'%}">Statistics</a>
            {%endif%}
            {%if request.user%}
              <a>Logout</a>
            {%else%}
              <a>Login</a>
            {%endif%}
            
          </div>
          <div class="footer-social-tabs">
            <a><em class="fab fa-facebook-f icon-color"></em></a
            ><a><em class="fab fa-twitter icon-color"></em></a
            ><a><em class="fab fa-linkedin-in icon-color"></em></a
            ><a><em class="fab fa-instagram icon-color"></em></a>
          </div>
        </div>
        <div class="copyright-bar">©2021 Justeece Inc. All rights reserved</div>
      </div>
      {% block javascript %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'lib/jquery/index.js' %}"></script>
      <script src="{% static 'js/common.js' %}"></script>
      <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.js' %}"></script>
      <script src="{% static 'lib/fontawesome/js/all.min.js' %}"></script>
      <script src="{% static 'lib/bootstrap-select-1.13.14/dist/js/bootstrap-select.min.js' %}"></script>
      <script>

        $(document).ready(function () {
          var alert = $(".alert-container");
          alert.hide();
            alert.slideDown();
            window.setTimeout(function() {
              alert.slideUp();
            }, 2500);
        })

      </script>
    {% endblock %}
    {% block extrascript %}
    {% endblock extrascript %}
    </body>
  </html>