justeece/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('confirm/<token>/<id>',
        VerificationView.as_view(), name='email_confirmation'),    
    path('forgotpassword/', ForgotPasswordRequestView.as_view(),
        name="forgot-password"),
    path('reset_password/<emailtype>/<token>/<id>',
        ResetPasswordView.as_view(), name='resetpassword'),
    path('reset-password-success/', ResetPasswordSuccessView.as_view(),
        name="reset_password_success"),   
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_list/<data>', UserListView.as_view(), name='profile'),
    path('email-verification-confirmation/', EmailVerificationConfirmationLinkView.as_view(), 
        name="email_verification_confirmation"),
    path('resendverification/<email>',
        ResendVerificationToken.as_view(), name='resendverification'),
    path('personal-details/',
        PersonalDetailsView.as_view(), name='personal-details'),
    path('dynamic-dropdonws/',
        DynamicDropdowns.as_view(), name='dynamic-dropdonws'),
    path('search_user/',
        SearchUserView.as_view(), name='search-user'),  
    path('create_cover_letter/',
        CreateCoverLetterView.as_view(), name='create-cover-letter'),  
    path('send_cover_letter/',
        SendCoverLetterView.as_view(), name='send-cover-letter'),   
    path('send_reference_email/',
        SendReferenceEmailView.as_view(), name='send-reference-email'),   
    path('add_reference/<int:id>',reference, name='add-reference'),
    path('unsubscribe/<int:id>',unsubscribe, name='unsubscribe')

]

justeece/app/urls.py
from django.contrib import admin
from django.urls import path
from app.views import TestimonialView, SearchView, AboutUsView

app_name = 'app'

urlpatterns = [
    path('testimonial/', TestimonialView.as_view(), name='testimonial'),
    path('search/', SearchView.as_view(), name='search'),
    path('aboutus/', AboutUsView.as_view(), name='about-us'),
]

justeece/contracts/urls.py
from django.contrib import admin
from django.urls import path
from contracts.views import *

app_name = 'contracts'

urlpatterns = [
    path('', ContractsLandingPageView.as_view(), name='contract-landing-page'),
    path('create_contract', CreateContractView.as_view(), name='create-contract'),
    path('create_contract_type/', CreateContractTypeView.as_view(), name='create-contract-type'),
    path('render_contract_type/',CreateContractTypeView.as_view(), name='render-contract'),
    # path('edit_contract/<int:contract_id>', CreateContractView.as_view(), name='edit-contract'),
    path('edit_contract/<int:contract_id>', EditContractView.as_view(), name='edit-contract'),
    path('contract_confirmation/<int:contract_id>', ContractConfirmationView.as_view(), name='contract-confirmation'),
    path('contract_completion/', ContractCompletionView.as_view(), name='contract-completion'),
    path('successview/', SuccessView.as_view(), name='successview'),
    path('submit_contract/<int:contract_id>', SubmitContract.as_view(), name='submit-contract'),
    path('contracts/', MyContractsView.as_view(), name='my-contracts'),
    path('contract_detail/<int:id>', ContractDetailView.as_view(), name='contract-detail'),
    path('update_contract/<int:id>', UpdateContractView.as_view(), name='update-contract'),
    path('contract_template/', TemplateContractView.as_view(), name='contract-template'),
    path('cancel_complete_contract/<int:id>', CancelCompleteContractView.as_view(), name='cancel-complete-contract'),
    path('search/', TemplateContractSearchView.as_view(), name='templatesearch'),
]

justeece/justeece/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import DashboardView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='signup'),
    path('providers/',  SignupView.as_view(), name='provider'),
    path('vendors/',  SignupView.as_view(), name='vendor'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contracts/', include('contracts.urls', namespace='contracts')),
    path('app/', include('app.urls', namespace='app')),
    path('manager/', include('manager.urls', namespace='manager')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

justeece/contracts/models.py
from django.db import models
from justeece.core.utils import TimestampedModel
from accounts.models import User
from app.models import S3ImageField
# Create your models here.

class ContractTypeModel(TimestampedModel):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name    

class ContractsModel(TimestampedModel):

    DRAFT = 1
    PENDING = 2
    IN_PROGRESS = 3
    COMPLETED = 4
    CANCELED = 5
    DISPUTE = 6
    REJECTED = 7

    CONTRACT_STATUS_CHOICES = (
        (DRAFT, ('Draft')),
        (PENDING, ('Pending')),
        (IN_PROGRESS, ('In Progress')),
        (COMPLETED, ('Completed')),
        (CANCELED, ('Canceled')),
        (DISPUTE, ('Dispute')),
        (REJECTED, ('Rejected'))
    )
    contract_name = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by_user")
    created_with = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_with_user", null=True, blank=True)
    created_with_email = models.EmailField(max_length=150, null=True, blank=True)
    contract_type = models.ForeignKey(ContractTypeModel, on_delete=models.CASCADE, related_name="create_contract_type")
    subcategory = models.CharField(max_length=100)
    contract_start_date = models.DateField(null=True, blank=True)
    contract_end_date = models.DateField(null=True, blank=True)
    summary = models.TextField(max_length=500)
    payment_included = models.BooleanField(default=False)
    amount = models.BigIntegerField(null=True, blank=True)
    status = models.SmallIntegerField(choices=CONTRACT_STATUS_CHOICES, default=DRAFT)
    contract_completed_date = models.DateField(null=True, blank=True)
    
    class Meta:
        db_table = "create_contract"
        verbose_name = "Contract"
        verbose_name_plural = "Contracts"

    def __str__(self):
        return self.contract_name


class EndContractReasonChoiceModel(TimestampedModel):
    reason = models.CharField(max_length=100)

    class Meta:
        verbose_name = "End Contract Reason Choice"
        verbose_name_plural = "End Contract Reason Choices"

    def __str__(self):
        return str(self.reason)

class RejectContractReasonChoiceModel(TimestampedModel):
    reason = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Reject Contract Reason Choice"
        verbose_name_plural = "Reject Contract Reason Choices"

    def __str__(self):
        return str(self.reason)

class CancelContractReasonChoiceModel(TimestampedModel):
    reason = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Cancel Contract Reason Choice"
        verbose_name_plural = "Cancel Contract Reason Choices"

    def __str__(self):
        return str(self.reason)

class ContractCloseFeedback(TimestampedModel):
    REJECT_CONTRACT = 1
    ACCEPT_CONTRACT = 2
    END_CONTRACT = 3
    CANCEL_CONTRACT = 4

    STATUS_CHOICES = (
        (REJECT_CONTRACT, ('Reject Contract')),
        (ACCEPT_CONTRACT, ('Accept Contract')),
        (END_CONTRACT, ('End Contract')),
        (CANCEL_CONTRACT, ('Cancel Contract')),
    )

    contract = models.ForeignKey(
        ContractsModel,
        on_delete=models.DO_NOTHING,
        related_name="contract_feedback"
    )
    status = models.SmallIntegerField(choices=STATUS_CHOICES)
    feedback = models.TextField(max_length=200, null=True, blank=True)
    end_contract_reason = models.ForeignKey(
        EndContractReasonChoiceModel, 
        on_delete=models.DO_NOTHING, null=True, blank=True
        )
    reject_contract_reason = models.ForeignKey(
        RejectContractReasonChoiceModel,
        on_delete=models.DO_NOTHING, null=True, blank=True
    )
    cancel_contract_reason = models.ForeignKey(
        CancelContractReasonChoiceModel,
        on_delete=models.DO_NOTHING, null=True, blank=True
    )
    rating = models.SmallIntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.contract.contract_name


class ContractTemplateTag(TimestampedModel):
    tag = models.CharField(max_length=40)

    def __str__(self):
        return self.tag


class ContractTemplate(TimestampedModel):
    title = models.CharField(max_length=60)
    description = models.CharField(max_length=200)
    agreement = models.TextField(blank=True)
    logo =  S3ImageField(upload_to='contract_image', null=True, blank=True)
    tag = models.ManyToManyField(ContractTemplateTag)
    #logo = models.ImageField(upload_to ='uploads/', null=True, blank=True)
    contract_type = models.ForeignKey(ContractTypeModel, on_delete=models.CASCADE, 
                    related_name="contract_type", null=True, blank=True)

    def __str__(self):
        return self.title

justeece/contracts/forms.py
import datetime
from django import forms
from django.forms import ModelChoiceField
from django.urls import reverse_lazy
from django.contrib import messages as flash_messages
from contracts.models import ContractsModel, ContractTypeModel, ContractCloseFeedback, CancelContractReasonChoiceModel, \
    RejectContractReasonChoiceModel, EndContractReasonChoiceModel
from app.email import Email
from contracts import messages

class CreateContractForm(forms.ModelForm):
   
    class Meta:
        model = ContractsModel

        fields = ['contract_name', 'created_by', 'contract_type', 
        'subcategory', 'contract_start_date','contract_end_date', 
        'summary', 'payment_included', 'amount', 'created_with_email']

    def __init__(self, request=None, user=None, contract=None, *args, **kwargs):
        super(CreateContractForm, self).__init__(*args, **kwargs)
        
        self.fields['contract_type'].queryset = ContractTypeModel.objects.all()
    #     self.request = request
        # self.user = user
        # self.contract = contract
        self.fields['contract_type'].empty_label = None

    # def clean_created_by(self):
    #     created_by = User.objects.get(id=self.user.id)
    #     return created_by

    # def clean(self):
    #     cleaned_data = super(CreateContractForm, self).clean()
    #     if cleaned_data['contract_end_date'] < cleaned_data['contract_start_date']:
    #         self.add_error('contract_start_date', "Contract's end date cannnot be greater than the start date. ")
    #     return cleaned_data

    # def save(self):
    #     if self.contract:
    #         ContractsModel.objects.filter(id=self.contract.id).update(**self.cleaned_data)
    #     else:
    #         ContractsModel.objects.create(**self.cleaned_data)
    #     return self
    
class CreateContractTypeForm(forms.ModelForm):
   
    name = forms.CharField(required=True)
    
    class Meta:
        model = ContractTypeModel
        fields = ['name']

class UpdateContractForm(forms.ModelForm):
    cancel_contract_reason = ModelChoiceField(queryset=CancelContractReasonChoiceModel.objects, empty_label=None, required=False)
    reject_contract_reason = ModelChoiceField(queryset=RejectContractReasonChoiceModel.objects, empty_label=None, required=False)
    end_contract_reason = ModelChoiceField(queryset=EndContractReasonChoiceModel.objects, empty_label=None, required=False)
    
    class Meta:
        model = ContractCloseFeedback
        fields = "__all__"
    
    def __init__(self, contract_id=None, request=None, *args, **kwargs):
        self.contract_id = contract_id
        self.request = request
        self.contract = ContractsModel.objects.filter(id=self.contract_id)
        super(UpdateContractForm, self).__init__(*args, **kwargs)

    def save(self):        
        update_to = self.request.GET.get('update')
        self.cleaned_data['contract'] = self.contract[0]
        contract_detail = reverse_lazy('contracts:contract-detail', kwargs={'id':self.contract[0].id})
        contract_detail = '%s://%s/%s' % (self.request.scheme, self.request.get_host(), contract_detail[1:])
        if self.request.method == 'POST':
            if update_to == 'reject':
                status = ContractsModel.REJECTED
                self.contract.update(status=status)
            elif update_to == 'accept':
                status = ContractsModel.IN_PROGRESS
                self.contract.update(status=status)
            elif update_to == 'cancel':
                status = ContractsModel.CANCELED
                self.contract.update(status=status)
            elif update_to == 'end':
                status = ContractsModel.COMPLETED
                self.contract.update(status=status, contract_completed_date=datetime.datetime.now())
        Email(self.contract[0].created_by.email, messages.CONTRACT_STATUS_UPDATED).message_from_template('contracts/email/contract_status_updated.html',
                                                                        {'first_name': self.contract[0].created_by.first_name,
                                                                        'last_name': self.contract[0].created_by.last_name,
                                                                        'contract_name': self.contract[0].contract_name,
                                                                        'created_with_email': self.contract[0].created_with.email,
                                                                        'status': self.contract[0].get_status_display(),
                                                                        'comment': self.cleaned_data.get('feedback'),
                                                                        'contract_detail': contract_detail},
                                                                        self.request).send()
        flash_messages.success(
            self.request,
            messages.CONTRACT_STATUS_UPDATED
        )    
        return super().save()


class TemplateContractSearchForm(forms.Form):
    search = forms.CharField(required=False)

justeece/contracts/templates/contracts/contract_cancelled.html
{% extends 'layout.html' %}{% load static %}
{% block extrastyles %}
<link
rel="stylesheet"
href="{% static 'lib/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}"
/>    
<link rel="stylesheet" href="{% static 'css/landingPage/index.css' %}" />
<link
rel="stylesheet"
href="{% static 'lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'css/modal/index.css' %}"
/>
<link rel="stylesheet" href="{% static 'css/contract/index.css' %}" />
{% endblock %}
{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="form-wrapper contract-page-parent-wrapper">
          <div class="contract-page">
            <div class="contract-page-image-section">
              <img src="{% static 'images/cancelled_contract.svg' %}" alt="contract" />
            </div>

            <!-- Contract section for last page start -->
            <h2 class="form-header">You have <span class="text-danger">cancelled</span> your contract</h2>
            <h5 class="form-header-small">
              <span
                >An email has been sent to
                <span>{{contract.created_by.email}}</span> to update about the same.</span
              ><span>
                this contract. We will notify you if any changes are
                needed</span
              >
            </h5>
            <div class="buttons-wrapper contract-complete">
              <a href="{% url 'accounts:dashboard' %}" class="btn btn-outline-primary">Go to main page</a>
            </div>
            <!-- Contract section for last page end -->
          </div>
        </div>
      </div>
    </div>
{% endblock %}

justeece/contracts/templates/contracts/contract_completion.html
{% extends 'layout.html' %}{% load static %}
{% block extrastyles %}
<link
rel="stylesheet"
href="{% static 'lib/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}"
/>    
<link rel="stylesheet" href="{% static 'css/landingPage/index.css' %}" />
<link
rel="stylesheet"
href="{% static 'lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'css/modal/index.css' %}"
/>
<link rel="stylesheet" href="{% static 'css/contract/index.css' %}" />
{% endblock %}
{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="form-wrapper contract-page-parent-wrapper">
          <div class="contract-page">
            <div class="contract-page-image-section">
              <img src="{% static 'images/contract.svg' %}" alt="contract" />
            </div>

            <!-- Contract section for last page start -->
            <h2 class="form-header">Your contract has been created</h2>
            <h5 class="form-header-small">
              <span
                >An email has been sent to
                <span>{{email}}</span> to accept</span
              ><span>
                this contract. We will notify you if any changes are
                needed</span
              >
            </h5>
            <div class="buttons-wrapper contract-complete">
              <a href="{% url 'accounts:dashboard' %}" class="btn btn-outline-primary">Go to main page</a>
            </div>
            <!-- Contract section for last page end -->
          </div>
        </div>
      </div>
    </div>
{% endblock %}

justeece/contracts/templates/contracts/contract_confirmation.html
{% extends 'layout.html' %}{% load static %}
{% block extrastyles %}
<link
rel="stylesheet"
href="{% static 'lib/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}"
/>    
<link rel="stylesheet" href="{% static 'css/landingPage/index.css' %}" />
<link
rel="stylesheet"
href="{% static 'lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'css/modal/index.css' %}"
/>
<link rel="stylesheet" href="{% static 'css/contract/index.css' %}" />
<style>
  
  .contract-title{
    font-weight: 800;
    margin-left: 75px;
    text-decoration: underline;
  }

  .contract-bold{
    font-weight: 700;
    
  }
</style>
{% endblock %}

{% block content %}
    <div class="content-wrapper">
      <div class="container">
        <div class="form-wrapper contract-page-parent-wrapper">
          <div class="contract-page">
            <div class="contract-page-image-section">
              <img src="{% static 'images/contract.svg' %}" alt="contract" />
            </div>
            <h2 class="form-header">Your contract is ready to be created</h2>
            <h5 class="form-header-small">View contract details below</h5>
            <!-- Contract section for last page start -->
            <!-- <h2 class="form-header">Your contract has been created</h2> -->
            <!-- <h5 class="form-header-small">
              <span
                >An email has been sent to
                <span>a.kutsan1994@gmail.com</span> to accept</span
              ><span>
                this contract. We will notify you if any changes are
                needed</span
              >
            </h5> -->
            <!-- <div class="buttons-wrapper">
              <button class="btn btn-outline-primary">Go to main page</button>
            </div> -->
            <!-- Contract section for last page end -->
            <div class="contract-wrapper">
              <div class="contract-wrapper-section">
                <div class="contract-wrapper-header">
                  <div class="contract-wrapper-header-left">
                    <span class="dispute-wrapper-head">Status of contract</span
                    ><span class="dispute-wrapper"
                      ><img
                        src="{% static 'images/contract-dispute.svg' %}"
                        alt="dispute"
                      /><span>{{contract.get_status_display}}</span></span
                    >
                  </div>
                  <div class="contract-wrapper-header-right">
                    <div class="contract-wrapper-header-right-head">
                      <span>{{contract.created_with_email}}</span
                      ><span>
                        <img
                          class="card-img-top"
                          src="{% if contract.created_with.profile_photo %}{{contract.created_with.profile_photo.url}}{% else %}{% static 'images/profile_img.png' %} {% endif %}"
                          alt=""
                        />
                      </span>
                    </div>
                  </div>
                </div>
                <div class="contract-wrapper-content">
                  <div class="contract-wrapper-content-section">
                    <div class="contract-wrapper-content-section-wrapper">
                      <div
                        class="contract-wrapper-content-section-wrapper-child"
                      >
                        <div class="contract-wrapper-content-section-header">
                          Contract type:
                        </div>
                        <div class="contract-wrapper-content-section-content">
                          {{contract.contract_type}}
                        </div>
                      </div>
                      <div
                        class="contract-wrapper-content-section-wrapper-child"
                      >
                        <div class="contract-wrapper-content-section-header">
                          Subcategory:
                        </div>
                        <div class="contract-wrapper-content-section-content">
                          {{contract.subcategory}}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="contract-wrapper-content-section">
                    <div class="contract-wrapper-content-section-header">
                      Contract summary:
                    </div>
                    <div class="contract-wrapper-content-section-content">
                      {{contract.summary | safe}}
                    </div>
                  </div>
                  <div class="contract-wrapper-content-section">
                    <div class="contract-wrapper-content-section-wrapper">
                      <div
                        class="contract-wrapper-content-section-wrapper-child"
                      >
                        <div class="contract-wrapper-content-section-header">
                          Contract start date:
                        </div>
                        <div class="contract-wrapper-content-section-content">
                          {{contract.contract_start_date}}
                        </div>
                      </div>
                      <div
                        class="contract-wrapper-content-section-wrapper-child"
                      >
                        <div class="contract-wrapper-content-section-header">
                          Contract end date:
                        </div>
                        <div class="contract-wrapper-content-section-content">
                          {{contract.contract_end_date}}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="contract-wrapper-content-section">
                    <div class="contract-wrapper-content-section-wrapper">
                      <div
                        class="contract-wrapper-content-section-wrapper-child contract-wrapper-content-section-wrapper-child-last-section"
                      >
                        <div class="contract-wrapper-content-section-header">
                          Amount included
                        </div>
                        <div class="contract-wrapper-content-section-content">
                          ${{contract.amount}}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    class="contract-wrapper-content-section contract-wrapper-footer"
                  >
                    <a class="btn btn-outline-primary" href="{% url 'contracts:edit-contract' contract_id=contract.id %}">
                      Edit contract
                    </a>
                    <a class="btn btn-primary" href="{% url 'contracts:submit-contract' contract_id=contract.id %}">Create a contract</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

justeece/contracts/templates/contracts/contract_landing.html
{% extends 'layout.html' %}{% load static %}
{% block extrastyles %}
<link rel="stylesheet" href="{% static 'lib/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/landingPage/index.css' %}" />
<style>

  .card-profile {
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 0 0 20px 0;
    justify-content: center;
  }

  .card-img-top {
    max-width: 100px;
    border-radius: 50%;
    margin: 0px 10px 0 15px;
    box-shadow: 0px 3px 20px rgb(131 130 130 / 20%);
    width: 60px;
    height: 60px;
  }

  #search-bar {
    display: block;
    margin: .25em 0 0;
    width: 100%;
    padding: .25em .5em;
    font-size: 1.2em;
  }

  .output,
  #search-bar {
    background: #fff;
    border: 1px solid #767676;
  }

  .prediction-item {
    padding: .5em .75em;
    transition: color 0.2s, background 0.2s;
  }

  .output {
    list-style: none;
    width: 100%;
    min-height: 0px;
    border-top: 0 !important;
    color: #767676;
    font-size: .75em;
    transition: min-height 0.2s;
    position: absolute;
    z-index: 5;
  }
  .output:hover .focus {
    background: #fff;
    color: #767676;
  }


  .prediction-item:hover {
    cursor: pointer;
  }

  .prediction-item:hover,
  .focus,
  .output:hover .focus:hover {
    background: #ddd;
    color: #333;
  }
  .noclick {
    pointer-events: none;
  }

  .prediction-item strong {
    color: #333;
  }

  .prediction-item:hover strong {
    color: #000;
  }

  /* p { margin-top: 1em; }
h1 { color: #439973; padding-bottom: 5px; border-bottom: 2px dotted #439973; font-family: 'Patua One'; }
span { font-size: 1.5em; } */
  .down_arrows {
    padding: 60px;
  }
</style>
<link rel="stylesheet" href="{% static 'lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/modal/index.css' %}" />
<link rel="stylesheet" href="{% static 'css/contract/landing.css'%}" />
{% endblock %}
{% block content %}
<div class="content-wrapper">
  <div class="container header">
    <div class="form-wrapper landing-page-parent-wrapper">
      <h5 id="header" class="form-header-small">
        World's #1 Online Contract Performance Database
      </h5>
      <h2 id= 'header-hs' class="form-header">Check Contract History Here</h2>
      <form class="landing-page abc" action="{% url 'app:search' %}" method="get">
        <div class="form-group ">
          <div class="input-field-wrapper">
            <input type="text" placeholder="Enter a person's phone number or email" name="search"
              class="form-field form-control" autocomplete="off" />
            <span class="email-icon "><img src="{% static 'images/search-icon.svg' %}" alt="search" /></span>
          </div>
          <button type="submit" class="btn btn-primary">Check</button>
        </div>
      </form>
      <!-- logged in section -->
      {% if request.user.is_authenticated %}
        <h1 class= 'send-header'>Send Contract to Anyone <span>in Just 3 Clicks</span></h1>
        <div class="row contract-page-link-row">
          
          <a class="contract-page-link col-md-4 mr-5" href="{% url 'contracts:contract-template' %}">
          <div>
              <h3 class="contract-page-link-h3">Template Contracts</h3>
                <img src="{% static 'images/Frame 3843.svg' %}" alt="">
          </div>
          </a>
          <a class="contract-page-link mr-5 col-md-4" href="#">
            <div>
                <h3 class="contract-page-link-h3">Custom Contracts</h3>
                  <img src="{% static 'images/Frame 3843.svg' %}" alt="">
            </div>
            </a>
        </div>
      {% endif %}
      <!-- unlogged in section ends-->
      <h2 class="form-header">How it works</h2>
      <h5 class="align-middle form-header-small">
        Simply follow the three steps below to obtain information about a person
      </h5>
      <div class="landing-page-wrapper how-it-works">
        <div class="image-wrapper">
          <span class="image-count">01</span>
          <span class="image-wrapper-image"><img src="{% static 'images/image1.svg' %}" alt="image" /></span>
          <span class="image-wrapper-text "><span>Provide the phone number or email</span> of the person you
            want to deal with</span>
        </div>
        <div class="image-wrapper">
          <span class="image-count">02</span>
          <span class="image-wrapper-image "><img src="{% static 'images/image2.svg' %}" alt="image" /></span>
          <span class="image-wrapper-text"><span>Find the person here</span> and see whether he or she is
            a trustworthy person</span>
        </div>
        <div class="image-wrapper">
          <span class="image-count">03</span>
          <span class="image-wrapper-image"><img src="{% static 'images/image3.svg' %}" alt="image" /></span>
          <span class="image-wrapper-text ">If you are satisfied with the findings
            <span>begin dealing with the person</span></span>
        </div>
      </div>
    </div>
  </div>
</div>
    {% endblock %}
    {% block extrascript %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'lib/OwlCarousel2-2.3.4/dist/owl.carousel.js' %}"></script>
    <script src="{% static 'js/landingPage.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.js' %}"></script>
    {% endblock %}

justeece/contracts/templates/contracts/contract_type.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>      

justeece/contracts/templates/contracts/success.html
SUCCESS